style: adjust terraform error message
Added coloring to the missing terraform binaries error message.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -12,8 +12,8 @@ if command -v terraform > /dev/null
 then
   terraform fmt ./terraform
 else
-  echo "Terraform could not be found in the system binaries!"
-  echo "Please make sure it's setup properly an the 'terraform' command is available in the path."
+  >&2 echo "$(tput setaf 1)Terraform could not be found in the system binaries!"
+  >&2 echo "$(tput setaf 1)Please make sure it's setup properly an the 'terraform' command is available in the path.$(tput sgr0)"
 fi
 
 # Add changes to commit
